import React from "react";
import Head from "next/head";

const SignIn = () => {
  return (
    <div>
      <Head>
        <title>Sign In</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Sign In</h1>
    </div>
  );
};

SignIn.layout = "defaultLayout";
export default SignIn;
